# Generated by Django 4.2.8 on 2023-12-04 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forairy_app', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
